### ISSUE TITLE
Unable to use nuget package due to load error

### ISSUE THREAD

**Issue by AlucardBNS** [AmpScm/SharpProj#21]
When trying to run an app with this nuget package, I receive the following error: _System.BadImageFormatException: 'Could not load file or assembly 'SharpProj, Version=8.2001.106.0, Culture=neutral, PublicKeyToken=3a930e679d9a0873'. An attempt was made to load a program with an incorrect format.'_

I'm using the package in a small console application. It is .Net 5

I have tried version 8.2001.106.0 down to 8.1.26...

**Comment by rhuijben** [comment]
This looks like an issue loading an X86 assembly in an X64 project or the other way around. There is also a runtime requirement on the Visual C++ runtime for the unmanaged parts of the code inside SharpProj, so make sure you have that installed on older platforms. (Should be installed by default on Win10/Win11, and with Visual Studio).

The assemblies are not platform independent, but NuGet should have warned for you if that is the issue. The unmanaged proj library is linked into SharpProj in a way that is not (yet) portable.

**Comment by rhuijben** [comment]
Issue appears to be stale.
